<?php
ale_demo_media::add_image_to_media_gallery('ale_main_logo',"http://ellitheme.pixrow.co/media/library/logo-1.png");
ale_demo_media::add_image_to_media_gallery('ale_logo_big',"http://ellitheme.pixrow.co/media/library/logo-big.png");
ale_demo_media::add_image_to_media_gallery('ale_left_leave',"http://ellitheme.pixrow.co/media/library/leave-left.png");
ale_demo_media::add_image_to_media_gallery('ale_fryingpen',"http://ellitheme.pixrow.co/media/pages/fryingpen.png");
ale_demo_media::add_image_to_media_gallery('ale_home_iconglass',"http://ellitheme.pixrow.co/media/pages/homepage1-icon1.png");
ale_demo_media::add_image_to_media_gallery('ale_home_icondish',"http://ellitheme.pixrow.co/media/pages/homepage1-icon2.png");
ale_demo_media::add_image_to_media_gallery('ale_home_iconstar',"http://ellitheme.pixrow.co/media/pages/homepage1-icon3.png");
ale_demo_media::add_image_to_media_gallery('ale_home_iconbook',"http://ellitheme.pixrow.co/media/pages/service-icon-book.png");
ale_demo_media::add_image_to_media_gallery('ale_home_iconshop',"http://ellitheme.pixrow.co/media/pages/service-icon-shop.png");
ale_demo_media::add_image_to_media_gallery('ale_home_iconsun',"http://ellitheme.pixrow.co/media/pages/service-icon-sun.png");
ale_demo_media::add_image_to_media_gallery('ale_bluefish',"http://ellitheme.pixrow.co/media/pages/blueplate.png");
ale_demo_media::add_image_to_media_gallery('ale_whiteplate',"http://ellitheme.pixrow.co/media/pages/white-plaate.png");
ale_demo_media::add_image_to_media_gallery('ale_header_slider1',"http://ellitheme.pixrow.co/media/pages/homepage1-slider1.jpg");