<?php
ale_demo_media::add_image_to_media_gallery('ale_team1',"http://ellitheme.pixrow.co/media/pages/team1.jpg");
ale_demo_media::add_image_to_media_gallery('ale_team2',"http://ellitheme.pixrow.co/media/pages/team2.jpg");
ale_demo_media::add_image_to_media_gallery('ale_team3',"http://ellitheme.pixrow.co/media/pages/team3.jpg");
ale_demo_media::add_image_to_media_gallery('ale_header_slider2',"http://ellitheme.pixrow.co/media/pages/homepage1-slider2.jpg");
ale_demo_media::add_image_to_media_gallery('ale_header_slider3',"http://ellitheme.pixrow.co/media/pages/homepage1-slider3.jpg");
ale_demo_media::add_image_to_media_gallery('ale_orange_fruits',"http://ellitheme.pixrow.co/media/pages/homepage1-1.jpg");
ale_demo_media::add_image_to_media_gallery('ale_home1_prlx',"http://ellitheme.pixrow.co/media/pages/homepage1-prlx.jpg");
ale_demo_media::add_image_to_media_gallery('ale_menugallery_icon',"http://ellitheme.pixrow.co/media/pages/menugallery-icon.png");
ale_demo_media::add_image_to_media_gallery('ale_menugallery_cake',"http://ellitheme.pixrow.co/media/pages/2.jpg");