<?php
ale_demo_media::add_image_to_media_gallery('ale_project_amazing',"http://ellitheme.pixrow.co/media/projects/project1.jpg");
ale_demo_media::add_image_to_media_gallery('ale_project_traditional',"http://ellitheme.pixrow.co/media/projects/project2.jpg");
ale_demo_media::add_image_to_media_gallery('ale_project_gastronomy',"http://ellitheme.pixrow.co/media/projects/project3.jpg");
ale_demo_media::add_image_to_media_gallery('ale_project_breakfast',"http://ellitheme.pixrow.co/media/projects/project5.jpg");
ale_demo_media::add_image_to_media_gallery('ale_project_fooddesign',"http://ellitheme.pixrow.co/media/projects/project7.jpg");
ale_demo_media::add_image_to_media_gallery('ale_service_orange',"http://ellitheme.pixrow.co/media/pages/servicepage-orange.jpg");
ale_demo_media::add_image_to_media_gallery('ale_home2_fishtexture',"http://ellitheme.pixrow.co/media/pages/homepage2-menutab1.jpg");
ale_demo_media::add_image_to_media_gallery('ale_home2_slider3',"http://ellitheme.pixrow.co/media/pages/homepage2-slider3.jpg");
ale_demo_media::add_image_to_media_gallery('ale_home2_sld1',"http://ellitheme.pixrow.co/media/pages/main_header.jpg");
ale_demo_media::add_image_to_media_gallery('ale_home2_sld2',"http://ellitheme.pixrow.co/media/pages/homepage2-sld.jpg");
ale_demo_media::add_image_to_media_gallery('ale_home2_cake1',"http://ellitheme.pixrow.co/media/pages/homepage2-cake1.jpg");
ale_demo_media::add_image_to_media_gallery('ale_home2_cake2',"http://ellitheme.pixrow.co/media/pages/homepage2-cake2.jpg");
ale_demo_media::add_image_to_media_gallery('ale_home2_orange_tab',"http://ellitheme.pixrow.co/media/pages/homepage2-tabs3.jpg");