<?php
ale_demo_media::add_image_to_media_gallery('ale_post_goodside',"http://ellitheme.pixrow.co/media/posts/the-good-side.jpg");ale_demo_media::add_image_to_media_gallery('ale_post_bestfood',"http://ellitheme.pixrow.co/media/posts/best-food.jpg");
ale_demo_media::add_image_to_media_gallery('ale_post_gettherich',"http://ellitheme.pixrow.co/media/posts/get-the-rich.jpg");
ale_demo_media::add_image_to_media_gallery('ale_post_mmmm',"http://ellitheme.pixrow.co/media/posts/mmmm.jpg");
ale_demo_media::add_image_to_media_gallery('ale_post_mmmmm',"http://ellitheme.pixrow.co/media/posts/mmmmm.jpg");
ale_demo_media::add_image_to_media_gallery('ale_post_yourdeserve',"http://ellitheme.pixrow.co/media/posts/your-deserve.jpg");
ale_demo_media::add_image_to_media_gallery('ale_post_gallery2',"http://ellitheme.pixrow.co/media/posts/post-gallery.jpg");
ale_demo_media::add_image_to_media_gallery('ale_woo_ceramiccup',"http://ellitheme.pixrow.co/media/woocommerce/ceramiccup-main.jpg");
ale_demo_media::add_image_to_media_gallery('ale_woo_ceramickettle',"http://ellitheme.pixrow.co/media/woocommerce/ceramickettle-main.jpg");
ale_demo_media::add_image_to_media_gallery('ale_woo_creativeplate',"http://ellitheme.pixrow.co/media/woocommerce/creativeplate-main.jpg");
ale_demo_media::add_image_to_media_gallery('ale_woo_freshcoffee',"http://ellitheme.pixrow.co/media/woocommerce/freshcoffee-main.jpg");
ale_demo_media::add_image_to_media_gallery('ale_woo_greenspices',"http://ellitheme.pixrow.co/media/woocommerce/greenspice-main.jpg");
ale_demo_media::add_image_to_media_gallery('ale_woo_honey1',"http://ellitheme.pixrow.co/media/woocommerce/honey1-main.jpg");
ale_demo_media::add_image_to_media_gallery('ale_woo_drylemon',"http://ellitheme.pixrow.co/media/woocommerce/drylemon-main.jpg");
ale_demo_media::add_image_to_media_gallery('ale_woo_jam',"http://ellitheme.pixrow.co/media/woocommerce/jam-main.jpg");
ale_demo_media::add_image_to_media_gallery('ale_woo_muffins',"http://ellitheme.pixrow.co/media/woocommerce/muffins.jpg");
ale_demo_media::add_image_to_media_gallery('ale_woo_bluefruit',"http://ellitheme.pixrow.co/media/woocommerce/bluefruit.jpg");
ale_demo_media::add_image_to_media_gallery('ale_woo_yellowcock',"http://ellitheme.pixrow.co/media/woocommerce/11.jpg");